# ignore all warnings from all pods
inhibit_all_warnings!

target 'SuperUnlocker' do
    platform :ios, 8.0
    pod 'libextobjc/EXTScope', '~> 0.4'
    pod 'ReactiveCocoa', '2.4.7'
end

target 'MacGuarder' do
    platform :osx, 10.7
    pod 'SSKeychain'
end
